title: Github pages rock  
author: devitalio
email: v.dol_s@hotmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  github pages tutorial clone

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  devitalio # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
